version: "3.9"

services:
  backend:
    build: back_end
    command: python challenge_me/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back_end:/code
    ports:
      - "8000:8000"
    network_mode: bridge

  frontend:
    depends_on:
      - backend
    build: front_end
    command: npm start
    volumes:
      - ./front_end:/app
    ports:
      - "80:80"
    network_mode: bridge
