version: "3.9"

services:
  backend:
    container_name: backendx
    build: back_end
    command: bash -c "python challenge_me/manage.py migrate && python challenge_me/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./back_end:/code
    ports:
      - "8000:8000"
    environment:
      - challengeme_production=${challengeme_production}
      - challengemedb_user=${challengemedb_user}
      - challengemedb_pwd=${challengemedb_pwd}
      - challengemedb_url=${challengemedb_url}
      - challengemedb_port=${challengemedb_port}
      - AWS_S3_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID}
      - AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY}
      - AWS_S3_STORAGE_BUCKET_NAME=${AWS_S3_STORAGE_BUCKET_NAME}

  frontend:
    container_name: frontendx
    depends_on:
      - backend
    build: front_end
    command: npm start
    ports:
      - "80:80"
