import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Grommet, Page, PageContent } from 'grommet';
import ChallengesTable from '../src/components/challengesTable'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Grommet plain>
        <Page kind="narrow">
          <PageContent background="light-3">
            <ChallengesTable />
          </PageContent>
        </Page>
      </Grommet>
    </div>
  )
}

export default Home
