import { Button, Container } from "@mui/material";
import type {
  GetServerSideProps,
  InferGetServerSidePropsType,
  NextPage
} from "next";
import Head from "next/head";
import Link from "next/link";
import ChallengesTable from "../src/components/challengesTable";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxWidth="sm">
        <ChallengesTable />
        <Link href="/create_challenge">
          <Button variant="contained">Create new challenge</Button>
        </Link>
      </Container>
    </div>
  );
};

export default Home;
