import { Box, Button, Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import {
  Challenge,
  NewChallengeShape,
  useChallengesClient
} from "../src/clients/challenges";
import { NewChallengeScheduleShape } from "../src/clients/challengeSchedules";
import ChallengesTable from "../src/components/challengesTable/ChallengesTable";
import CreateChallengeForm from "../src/components/createChallengeForm/CreateChallengeForm";
import CreateChallengeScheduleForm from "../src/components/createChallengeScheduleForm/CreateChallengeScheduleForm";
import CreateChallengeTypeForm from "../src/components/createChallengeTypeForm/CreateChallengeTypeForm";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [challenge, setChallenge] = useState<Challenge>();

  const { createChallenge } = useChallengesClient();

  const handleCreateChallenge = async (data: NewChallengeShape) => {
    return createChallenge(data).then((response) => setChallenge(response));
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CreateChallengeForm
        onCreateChallenge={handleCreateChallenge}
        challenge={challenge}
      />
      {challenge && (
        <Box sx={{ mt: 3 }}>
          <CreateChallengeScheduleForm challenge_id={challenge?.challenge_id} />
        </Box>
      )}
    </>
  );
};

export default Home;
