# Generated by Django 4.0.5 on 2022-06-23 22:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeSchedule',
            fields=[
                ('challenge_schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_goal', models.FloatField(validators=[django.core.validators.MinValueValidator(0.001)])),
                ('start_date', models.DateField()),
                ('day_frequency', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('challenge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge_app.challenge')),
                ('challenge_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge_app.challengetype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('challenge_id', 'user_id', 'challenge_type_id')},
            },
        ),
        migrations.CreateModel(
            name='ChallengeCompletionEntry',
            fields=[
                ('challenge_completion_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.001)])),
                ('challenge_schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge_app.challengeschedule')),
            ],
        ),
    ]
