# Generated by Django 4.0.6 on 2022-07-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0004_rename_type_id_challengetype_challenge_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengeschedule',
            old_name='total_goal',
            new_name='daily_goal',
        ),
    ]
