name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: "true"

      - name: Install front-end dependencies
        run: npm --prefix ./front_end install

      - name: Build front-end
        run: npm --prefix ./front_end run build

      - name: Generate Deployment Package
        run: zip -r deploy.zip . -x ./**/node_modules/**\*

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: "-"
          flags: "g"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ChallengeMe
          environment_name: Challengeme-env
          version_label: "challenge_me_${{ steps.format-time.outputs.replaced }}"
          region: eu-central-1
          deployment_package: deploy.zip
